[package]
name = "idem-handler"
version = "0.1.0"
edition = "2024"

[dependencies]
idem-handler-config = {path = "../idem-handler-config" }
async-trait = "0.1.88"
fnv = "1.0.7"

[dev-dependencies]
tokio = { version = "1.44.1" , features = ["macros", "rt"]}
